model: "gpt-4.1-mini"
toc_check_page_num: 20
max_page_num_each_node: 10
max_token_num_each_node: 20000
include_node_id: "yes"
include_node_summary: "no"
include_doc_description: "yes"
include_node_text: "no"
accuracy_threshold: 0.8
timeout_minutes: 10